server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/nttdata
    username: postgres
    password: postgres
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          batch_size: 128
          fetch_size: 128
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
    hibernate:
      ddl-auto: validate
    show-sql: true
feign:
  client:
    client-person: http://localhost:8080/api

